### PR TITLE
fix(DiseasystoreGoogleCovid19): allow URLs as source_conn

### LINKED ISSUE #60: DiseasystoreGoogleCovid19: fails to get features when source_conn is url
**Describe the bug**
When using the default value for the `source_conn` (the google API), `google_covid_19_metric` fails to properly retrieve data from the API.

**To Reproduce**
```
ds <- diseasystore::DiseasystoreGoogleCovid19$new(
  target_conn = DBI::dbConnect(RSQLite::SQLite()),
  start_date = as.Date("2020-03-01"),
  end_date = as.Date("2020-03-02")
)

ds$get_feature("n_hospital")   # Fails
```

**Expected behavior**
´diseasystore´ should work with when using the API directly

**Screenshots**
N/A

**Provide output from `sessionInfo()`**
N/A

* [x] I have checked that the bug is not already described in [open issues](https://github.com/ssi-dk/SCDB/issues?q=is%3Aopen)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by RasmusSkytte**
### Intent
Fixes #60 

### Approach
Before, the code assumed `source_conn` was a directory.
This is now changed by doing the following:

1) Validate that `source_conn` is either a directory or a URL
2) Determine the location of `by-age.csv` depending on whether `source_conn` is URL or directory

### Known issues
N/A

### Checklist

* [x] The PR passes all local unit tests
* [ ] I have documented any new features introduced
* [ ] If the PR adds a new feature, please add an entry in `NEWS.md`
* [x] A reviewer is assigned to this PR

### CODE REVIEW

File: R/DiseasystoreGoogleCovid19.R [hunk 1]
```diff
@@ -136,10 +136,28 @@ google_covid_19_metric <- function(google_pattern, out_name) {
       coll <- checkmate::makeAssertCollection()
       checkmate::assert_date(start_date, lower = as.Date("2020-01-01"), add = coll)
       checkmate::assert_date(end_date,   upper = as.Date("2022-09-15"), add = coll)
+      checkmate::assert(
```
Comment (marcusmunch) [inline R/DiseasystoreGoogleCovid19.R:139]: Does `dir.exists(source_conn)` (used below) always return `FALSE` for an FTP connection?

I would handle this more explicitly, replacing the assertion with if-elif-else to either set a variable (e.g. `source_type`) to "directory" or "url" and `stop()` if no conditions are met.

File: tests/testthat/test-DiseasystoreGoogleCovid19.R [hunk 2]
```diff
@@ -1,6 +1,19 @@
 test_that("DiseasystoreGoogleCovid19 works", {
 
-  # First we create a temporary directory for the Google COVID-19 data
+  # Check we can use the Google API directly
```
Comment (marcusmunch) [inline tests/testthat/test-DiseasystoreGoogleCovid19.R:3]: `ds` is not used for the remainder of this test (>150 lines of code).

[Tests should be specific (😇)](https://github.com/ssi-dk/diseasy/wiki/Diseasy-coding-standard#5-tests-should-be-specific). I strongly suggest that you write a separate test for this.

**Review by marcusmunch — CHANGES_REQUESTED** [review]

File: tests/testthat/test-DiseasystoreGoogleCovid19.R (hunk 2 above)
Comment (RasmusSkytte) [reply tests/testthat/test-DiseasystoreGoogleCovid19.R:3]: Created a separate issue https://github.com/ssi-dk/diseasystore/issues/63 for this to keep track of this.

File: R/DiseasystoreGoogleCovid19.R (hunk 1 above)
Comment (RasmusSkytte) [reply R/DiseasystoreGoogleCovid19.R:141]: Updated to be more robust (and to reuse the `checkmate::` checks rather than `dir.exists`)

Adding an `source_type` parameter to control the logic would, I think, mean large changes to the how we handle features in general since the number of arguments to `compute` will then change across `FeatureHandlers`.

**Review by marcusmunch — APPROVED** [review]

File: R/DiseasystoreGoogleCovid19.R (hunk 1 above)
Comment (RasmusSkytte) [reply R/DiseasystoreGoogleCovid19.R:141]: Ahh, I see. I will keep this in mind.
